---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Outils de développement:
    - Visual Studio Code:
        icon: vscode.png
        href: http://vscode.teleporteur.localhost
        description: IDE (Integrated Development Environment) développé par Microsoft.
